name: AutoGrade README

on: [push, pull_request]  # Runs grading on each submission

jobs:
  autograde:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Clones the student's repo

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install  # Install dependencies (if needed)

      - name: Run Grading Script
        run: node grade.js  # Run the grading script
